CREATE DATABASE LibraryDB;

USE LibraryDB;

CREATE TABLE Books(
   ID INT PRIMARY KEY     NOT NULL,
   TITLE          TEXT    NOT NULL,
   AUTHOR         TEXT    NOT NULL,
   PUBLICATION_YEAR INT  NOT NULL,
   AVAILABILITY   BOOLEAN DEFAULT TRUE
);

CREATE TABLE Users(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   EMAIL          TEXT    NOT NULL UNIQUE
);

CREATE TABLE Borrowings(
   USER_ID        INT     NOT NULL,
   BOOK_ID        INT     NOT NULL,
   BORROW_DATE    DATE    NOT NULL,
   RETURN_DATE    DATE,
   FOREIGN KEY (USER_ID) REFERENCES Users(ID),
   FOREIGN KEY (BOOK_ID) REFERENCES Books(ID),
   PRIMARY KEY (USER_ID, BOOK_ID, BORROW_DATE)
);
